# Matrices and Linear Algebra 

This module reviews the basic matrix operation and statistics concepts that are widely used in manipulating, processing, and describing data. The topics in the module may seem diverse, covering a variety of matrix functions. Students should have been exposed to these topics in high school and college math curriculum. However, you don't have to learn the math again to be data scientist. Python Numpy and Scipy libraries provide rich functions to automat many math operations. The key is to understand the python APIs and how to packages. 
  <h3>      [Numpy Package](http://www.numpy.org)    </h3>
NumPy is a well-developed Python package for scientific computing. It contains a powerful N-dimensional array object sophisticated (broadcasting) functions tools for integrating C/C++ and Fortran code useful linear algebra, Fourier transform, and random number capabilities Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.
NumPy is licensed under the BSD license, enabling reuse with few restrictions.
    # Numpy arrays and scalar
    Why do we need arrays while we have Python lists?
    1. Efficient operation - smaller storage spaces
    2. Uniformed data type in array
    3. Vectorization for faster computation 
 NumPy's arrays are more compact than Python lists. Access in reading and writing items is also faster with NumPy. Today, we are dealing with large datasets, usually gigabytes or terabytes of data. With 64-bit architecture, NumPy would get away with 4 GB limits and has the capacity to process large datasets. 
“A Python list is an array of pointers to Python objects, at least 4 bytes per pointer plus 16 bytes for even the smallest Python object (4 for type pointer, 4 for reference count, 4 for value -- and the memory allocators rounds up to 16). A NumPy array is an array of uniform values -- single-precision numbers takes 4 bytes each, double-precision ones, 8 bytes. Less flexible, but you pay substantially for the flexibility of standard Python lists!” – Quoted from Python user forum. 

       

In [3]:
# Create an array
import numpy as np

#create an array from list
a_array = np.array([1,3,5,7]) 
print(a_array)

#convert existing list to array
a_list = [2,4,6,8]
a_array = np.array(a_list)  

#auto conversion to uniform type
b_list = [1,'bc','3',4]       
b_array = np.array(b_list)  
print(b_array)
#include members in different data types
#the matrix operations won't apply 
c_list = [[1,2],3,{1:'4'}]    
c_array = np.array(c_list)   
print(c_array)

print(type(c_array))
print(c_array.shape)
print(c_array[0])

[1 3 5 7]
['1' 'bc' '3' '4']
[list([1, 2]) 3 {1: '4'}]
<class 'numpy.ndarray'>
(3,)
[1, 2]


In [4]:
# Create special arrays using built-in functions
# empty, eye, identity, ones, zeros, full, arange 
# https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html#from-existing-data 

# create 2x3x4 dimentional array without value signed
print(np.empty([2,3,4]))   
# create 2X3X4 dimentional array and assign 0 to all the 24 elements
print(np.zeros([2,3,4])) 
#Return a 2-D array with ones on the diagonal and zeros elsewhere.
#It's usually an NxN matrix for identity matrix
print(np.eye(4,3))
#another way to create identity matrix    
print(np.identity(4))  
#use arrange to create a 1D array 
print(np.arange(50,20,-6.3))  

[[[  6.23042070e-307   7.56587584e-307   1.37961302e-306   6.89805830e-307]
  [  1.06811422e-306   1.22383391e-307   8.01097889e-307   1.78020169e-306]
  [  7.56601165e-307   1.02359984e-306   1.33510679e-306   2.22522597e-306]]

 [[  1.24611674e-306   1.29061821e-306   6.23057349e-307   2.22522597e-306]
  [  1.06810268e-306   6.23052935e-307   2.22522053e-306   1.24611266e-306]
  [  1.42418172e-306   1.37961641e-306   1.22383391e-307   8.45610231e-307]]]
[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[ 50.   43.7  37.4  31.1  24.8]


In [5]:
# Multi-dimentional arrays

# Create the multi-dimentional list first
print(np.array([a_array,b_array]))  

# Create multi-dimnetional array from reshaping a one-dimnetional array
print(np.arange(24).reshape(2,3,4))

print(np.random.randn(24).reshape(2,3,4))



[['2' '4' '6' '8']
 ['1' 'bc' '3' '4']]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0.09381765  0.41250077  0.08355602 -0.06732592]
  [-0.45665131  0.57077646 -0.65198927  0.42812357]
  [-0.98993859 -0.56754292 -0.36912467  1.05799949]]

 [[-0.22045461 -0.97600192 -0.01772387  1.27187213]
  [-0.68619255  1.68921918 -0.55464025  0.06663586]
  [ 1.00190346  0.63924077 -2.25594024  0.73882858]]]


In [6]:
#Use numpy sort() to sort matrix members' values 

#create a 2D array
a = np.array([[9,4,3], [3,1,2], [6,4,9]])
print("The original matrix: \n", a)

#Sort the array in vertical direction
a.sort(axis=0)
print("\nSorted in the veritical direction: \n",a)

#sort the array in horizontal direction
#the default axis is the last axis, in this case it's 1
a.sort(axis=1)
print("\nSorted in the horizontal direction: \n", a)

#We can also compare the values and return the index numbers of the result
#argsort also take directions based on axises 
a = np.array([[9,4,3], [3,1,2], [6,4,9]])
print("The original matrix: \n", a)
print("\nSorted indexes in the veritical direction: \n",a.argsort(axis=0))




The original matrix: 
 [[9 4 3]
 [3 1 2]
 [6 4 9]]

Sorted in the veritical direction: 
 [[3 1 2]
 [6 4 3]
 [9 4 9]]

Sorted in the horizontal direction: 
 [[1 2 3]
 [3 4 6]
 [4 9 9]]
The original matrix: 
 [[9 4 3]
 [3 1 2]
 [6 4 9]]

Sorted indexes in the veritical direction: 
 [[1 1 1]
 [2 0 0]
 [0 2 2]]


In [7]:
#let's explore the use of other numpy functions

#create a 1D array from a list
a = [2,3,4,7,-1,0, 123,-5,2,-6,-1,4]
a = np.array(a)

#convert all the negative numbers to 0 using np.where()
a = np.where(a<0, 0, a)
print(a)

#make the array contain unique numbers only 
a = np.unique(a)
print(a)

#quiz: do not use where and unique to accomplish the above tasks
a = [2,3,4,7,-1,0, 123,-5,2,-6,-1,4] 
#the for loop is in low-efficiency
for index in range(len(a)):
    if a[index] < 0:
        a[index] = 0
print(a)
a = list(set(a))
print(a)


[  2   3   4   7   0   0 123   0   2   0   0   4]
[  0   2   3   4   7 123]
[2, 3, 4, 7, 0, 0, 123, 0, 2, 0, 0, 4]
[0, 2, 3, 4, 7, 123]


# Scalar (not Vector)

"The quantity is either a vector or a scalar. These two categories can be distinguished from one another by their distinct definitions: Scalars are quantities that are fully described by a magnitude (or numerical value) alone. Vectors are quantities that are fully described by both a magnitude and a direction. Vectors have magnitude and direction, scalars only have magnitude. By definition, speed is the scalar magnitude of a velocity vector. "   
                                                                            - physicsclassroom.com <br>
The scalar here is a one-dimensional array, a record in a database table. But in other language, vectors and scalars are interchangeable. Here, I just want to specify the difference from the definition of these two terms. In data science, a dataset contains multiple scalars (records) in the horizontal direction (row direction). The number of rows are the number of records. 
When we imported an n x m dimension array directly from a data file, it usually means that there are n records of m-dimensional scalar. When you operate on arrays. It's good practice to write the shape of the arrays out first.


In [8]:
# let's create two 2 x 3 arrays
a_array = np.array([[1,2,3],[4,5,6]])
b_array = 1/a_array

print(a_array)
print(a_array.shape)
print(b_array)
print(b_array.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 1.          0.5         0.33333333]
 [ 0.25        0.2         0.16666667]]
(2, 3)


In [9]:
# It's look at the numerical operations on numbers (integers, float numbers ...), we can use the 
# same set of operations on arrays. Another way to think it is that a number is 1 x 1 array. 

print(a_array*b_array)
print(np.multiply(a_array,b_array))

print(a_array/b_array)
print(np.divide(a_array,b_array))

print(a_array+b_array)
print(np.add(a_array,b_array))

print(a_array-b_array)
print(np.subtract(a_array,b_array))

print(a_array**2)
print(np.power(a_array,2))

print(a_array)




[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[  1.   4.   9.]
 [ 16.  25.  36.]]
[[  1.   4.   9.]
 [ 16.  25.  36.]]
[[ 2.          2.5         3.33333333]
 [ 4.25        5.2         6.16666667]]
[[ 2.          2.5         3.33333333]
 [ 4.25        5.2         6.16666667]]
[[ 0.          1.5         2.66666667]
 [ 3.75        4.8         5.83333333]]
[[ 0.          1.5         2.66666667]
 [ 3.75        4.8         5.83333333]]
[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]
[[1 2 3]
 [4 5 6]]


In [10]:
# Find, calculate values within array
print(a_array)
print(np.max(a_array))
print(np.min(a_array))
print(np.average(a_array))
print(np.mean(a_array))
print(np.sum(a_array)) 
print(np.var(a_array))

# only calculate along one direction by defining axis
print(np.min(a_array, axis=0))
print(np.mean(a_array,axis=0))
print(np.sum(a_array, axis=0))

#find statistical properties of data
data = np.random.randint(100, 500, 10)
print(np.mean(data))
print(np.median(data))
print(np.percentile(data,90))
print(np.var(data))
print(np.std(data))

import math
print(math.sqrt(np.var(data)))






[[1 2 3]
 [4 5 6]]
6
1
3.5
3.5
21
2.91666666667
[1 2 3]
[ 2.5  3.5  4.5]
[5 7 9]
268.7
272.5
412.5
10793.01
103.889412358
103.88941235756414


In [11]:
# Matrix multiplication 
# n x m * m x l => n x l
#np.dot(a_array,b_array)

a_array_T = a_array.T
print(a_array_T)
print(np.dot(a_array, a_array_T))   # 2x3 * 3x2 => 2x2
print(a_array.dot(a_array_T))       # both np.dot or array.dot work

[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


In [12]:
#slicing 
#similiar to Lists, slicing can be done on matrices 
a_array=np.array([[1,2],[3,4],[5,6]])

In [6]:
a_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
print(a_array[1,0])
print(a_array[1][0])
print(a_array[:2,1:])

3
3
[[2]
 [4]]


In [14]:
# a little algebra
# get the inverse of a SQUARE matrix

#import linalg module from scipy library which is built on top of numpy
from numpy import linalg

# generate a random 3 x 3 squre array
a_array=np.random.rand(3,3)
print(a_array)




[[ 0.35372813  0.8150995   0.80097182]
 [ 0.68330854  0.3366397   0.87002891]
 [ 0.16780693  0.76051358  0.39730775]]


In [15]:
a_inv = linalg.inv(a_array)
print(a_inv)

[[-6.44071916  3.48077246  5.36224586]
 [-1.53096503  0.07479099  2.922645  ]
 [ 5.65082602 -1.61330175 -5.34228996]]


In [16]:
print(a_array.dot(a_inv))

[[  1.00000000e+00   2.22044605e-16  -8.88178420e-16]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  4.44089210e-16  -1.11022302e-16   1.00000000e+00]]


In [18]:
#Exercise: use inverse of a matrix to solve linear equation 
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html
# solve the equation a x = b for x =>  x = b/a = a to the power of -1 times b
# now, let's consider a and b are matrics (b is a scalar -> n by 1 matrix)
# Let's start from a simple one 5x = 10 --> x = 2
a = np.array([[5]])  #make sure a is a n by n square matrix [[]]
b = np.array([10])
x = linalg.inv(a).dot(b)
print(x)

# Let's solve a real problem 
'''
answer is 2,3, 0.5 

5*x1 + 2.5*x2+ 4*x3 =  19.5
1.4*x1 + 2*x2 -1*x3 =  8.3
12*x1 -3*x2 -6*x3 =  12 

'''

a = np.array([[5, 2.5, 4], [1.4, 2, -1], [12, -3, -6]])
b = np.array([19.5, 8.3, 12])
x = linalg.inv(a).dot(b)
print(x)
print(a.dot(x)-b)  #verification: the result should be close to a scalar of zeros

#a faster and easier way to do it is to use .slove(a,b), but you have to know such such functions exist
# the rule of thumb is that if they exist, use them, don't re-invent the wheels
x1 = np.linalg.solve(a,b)
print(x1)





[ 2.]
[ 2.   3.   0.5]
[ -3.55271368e-15   0.00000000e+00  -3.55271368e-15]
[ 2.   3.   0.5]


In [ ]:
#Assignment:

def anomaly_detection(x):
    import math
    found = True
    while found: 
        for i in range(len(x)): 
            mean = (np.mean(x)*len(x)-x[i])/(len(x)-1)
            std = math.sqrt((np.std(x)**2*len(x)-(x[i]-mean)**2)/(len(x)-1))
            distance = abs((x[i]-mean)/std)
            if distance > 3:
                print("Remove {:6.2f} from the list because it's {:3.2f} times of standard deviation of the list without it.".format(x[i],distance)) 
                print("{:6.2f} is removed from the list!\n".format(x[i]))
                x = np.delete(x,i)
                found=True
                break
            found = False

    print("No more anomaly is detected!")